name: API CI
#on: [push] for repos with only one folder like ap or frontend

#When you have multiple projects inside one, do the config below
#This config pushes changes that occur in the api folder,
# the workflows folder, and the api-ci.yml file

on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

#Linter are static tests, then you have unit tests and e2e tests.

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run linter
        shell: bash
        run: npm run lint
  unit-test:
    #This creates a new machine
    #I picked 'ubuntu-latest' is because I have 'wsl' or
    #a 'linux kernel' running on a windows machine.
    runs-on: ubuntu-latest
    steps:
      #Lets clone our repo in the new machine
      - name: Checkout
        uses: actions/checkout@v2
      #Installing node
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json
      #Installing dependencies
      - name: install
        shell: bash
        run: npm ci
      #Running tests
      - name: run unit test
        shell: bash
        run: npm run test
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:14

    services:
      mongo-e2e:
        image: mongo:4.4
      ports:
        - 27017:27017
      env:
        MONGO_INITDB_ROOT_USERNAME: test
        MONGO_INITDB_ROOT_PASSWORD: test123

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
            shell: bash
            run: npm ci
      - name: run e2e
        shell: bash
        run: npm run e2e
        env:
          MONGO_DB_NAME=demo
          MONGO_URL=mongodb://test:test123@mongo-e2e:27017?retryWrites=true&writeConcern=majority
